[package]
name = "wintrap"
version = "0.1.0"
authors = ["Eliza Velasquez"]
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = ["minwindef", "windef", "consoleapi", "winuser", "errhandlingapi", "libloaderapi", "winbase"] }
lazy_static = "1.2"
crossbeam-channel = "0.3"
